version: '3.8'
services:
  API:
    image: "register.jar"
    ports:
      - "8080:8080"
    depends_on:
      PostgreSQL:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL.internal:5432/quiz_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  PostgreSQL:
    image: postgres
    ports:
      - "15432:15432"
    environment:
      - POSTGRES_PASSWORD = postgres
      - POSTGRES_USER = postgres
      - POSTGRES_DB = register
    volumes:
      #      - my-data:/var/lib/postgresql/data
      #      - ./data.sql
#      - ./init:/docker-entrypoint-initdb.d/
    logging:
      options:
        max-size: 10m
        max-file: "13"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5